# Generated by Django 4.1.7 on 2023-03-01 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0003_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='car',
            name='comments',
        ),
        migrations.AddField(
            model_name='account',
            name='account_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountManagement.account'),
        ),
    ]
