# Generated by Django 4.1.7 on 2023-03-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0004_remove_account_cars_remove_car_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AccountManagement.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='targetCar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AccountManagement.car'),
            preserve_default=False,
        ),
    ]
