# Generated by Django 4.1.7 on 2023-03-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0009_accountsession_createdate_car_createdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='account',
            new_name='account_uid',
        ),
    ]
