# Generated by Django 4.1.7 on 2023-03-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0010_rename_account_car_account_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='account_uid',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_authored', to='AccountManagement.account'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentReceiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='AccountManagement.account'),
        ),
    ]
