# Generated by Django 4.1.7 on 2023-03-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0011_rename_account_uid_car_account_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
