# Generated by Django 4.1.7 on 2023-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0013_account_isacitve_car_satilikmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
