# Generated by Django 4.1.7 on 2023-05-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0014_account_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='account',
            new_name='account_uid',
        ),
    ]
