# Generated by Django 4.1.7 on 2023-05-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0015_rename_account_car_account_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='account_uid',
            new_name='account',
        ),
    ]
