# Generated by Django 4.1.7 on 2023-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0017_remove_accountsession_id_remove_car_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carLicensePhotoLocationNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
