# Generated by Django 4.1.7 on 2023-05-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0018_car_carlicensephotolocationno'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(to='AccountManagement.account'),
        ),
    ]
