# Generated by Django 4.1.7 on 2023-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0019_account_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(default=None, to='AccountManagement.account'),
        ),
    ]
