# Generated by Django 4.1.7 on 2023-05-09 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0021_remove_comment_commentreceiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='targetCar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_targetCar', to='AccountManagement.car'),
        ),
    ]
