# Generated by Django 4.1.7 on 2023-05-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0022_alter_comment_targetcar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
